<?php

namespace App\Http\Controllers;

use App\Models\FieldJob;
use App\Models\Kecamatan;
use App\Services\TelegramService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PublicController extends Controller
{
    /**
     * Landing page (halaman utama public)
     */
    public function landing()
    {
        return view('pages.public.landing');
    }

    /**
     * Form lapor gangguan
     */
    public function reportForm()
    {
        $kecamatans = Kecamatan::orderBy('nama')->get();
        return view('pages.public.report', compact('kecamatans'));
    }

    /**
     * Store public report
     */
    public function storeReport(Request $request)
    {
        try {
            $request->validate([
                'reporter_name'  => 'required|string|max:100',
                'customer_id'    => 'required|string|max:50',
                'reporter_phone' => 'required|string|max:20',
                'title'          => 'required|string|max:255',
                'address'        => 'required|string|max:500',
                'kecamatan_id'   => 'required|exists:kecamatans,id',
                'description'    => 'nullable|string|max:1000',
                'latitude'       => 'nullable',
                'longitude'      => 'nullable',
            ], [
                'reporter_name.required'  => 'Mohon isi nama Anda.',
                'customer_id.required'    => 'Mohon isi No. Pelanggan Anda.',
                'reporter_phone.required' => 'Mohon isi nomor HP.',
                'title.required'          => 'Mohon pilih jenis gangguan.',
                'address.required'        => 'Mohon isi alamat lokasi.',
                'kecamatan_id.required'   => 'Mohon pilih kecamatan.',
            ]);


            // Photo upload has been removed as per new requirements
            $photoPath = null;

            // ticket_code auto-generated by FieldJob::boot()
            $job = FieldJob::create([
                'reporter_name'  => $request->reporter_name,
                'customer_id'    => $request->customer_id,
                'reporter_phone' => $request->reporter_phone,
                'source'         => 'public',
                'title'          => $request->title,
                'address'        => $request->address,
                'kecamatan_id'   => $request->kecamatan_id,
                'description'    => $request->description,
                'photo_before'   => $photoPath,
                'latitude'       => $request->latitude,
                'longitude'      => $request->longitude,
                'status'         => 'pending',
            ]);

            // Broadcast to technicians via Telegram and WhatsApp
            try {
                $telegram = new TelegramService();
                $telegram->broadcastJob($job);
            } catch (\Exception $e) {
                \Log::warning('Telegram broadcast failed: ' . $e->getMessage());
            }

            try {
                $fonnte = new \App\Services\FonnteService();
                $fonnte->broadcastJob($job);
            } catch (\Exception $e) {
                \Log::warning('Fonnte broadcast failed: ' . $e->getMessage());
            }

            return response()->json([
                'success'     => true,
                'ticket_code' => $job->ticket_code,
                'message'     => 'Laporan berhasil dikirim!',
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'errors'  => $e->errors(),
            ], 422);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan server: ' . $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Track ticket status
     */
    public function trackTicket(Request $request)
    {
        $ticket = null;
        $ticketCode = $request->query('kode');

        if ($ticketCode) {
            $ticket = FieldJob::with(['kecamatan', 'user'])
                ->where('ticket_code', $ticketCode)
                ->first();
        }

        return view('pages.public.track', compact('ticket', 'ticketCode'));
    }

    /**
     * Calculate average response time in minutes
     */
    private function getAverageResponse()
    {
        $jobs = FieldJob::whereNotNull('started_at')->get();
        if ($jobs->isEmpty()) return 0;

        $totalMinutes = 0;
        foreach ($jobs as $job) {
            $totalMinutes += $job->created_at->diffInMinutes($job->started_at);
        }
        return round($totalMinutes / $jobs->count());
    }
}
