<?php

namespace App\Http\Controllers;

use App\Models\FieldJob;
use App\Models\Kecamatan;
use App\Services\TelegramService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PublicController extends Controller
{
    /**
     * Landing page (halaman utama public)
     */
    public function landing()
    {
        return view('pages.public.landing');
    }

    /**
     * Form lapor gangguan
     */
    public function reportForm()
    {
        $kecamatans = Kecamatan::orderBy('nama')->get();
        return view('pages.public.report', compact('kecamatans'));
    }

    /**
     * Store public report
     */
    public function storeReport(Request $request)
    {
        try {
            $request->validate([
                'reporter_name'  => 'required|string|max:100',
                'customer_id'    => 'required|string|max:50',
                'reporter_phone' => 'required|string|max:20',
                'title'          => 'required|string|max:255',
                'address'        => 'required|string|max:500',
                'kecamatan_id'   => 'required|exists:kecamatans,id',
                'description'    => 'nullable|string|max:1000',
                'latitude'       => 'nullable',
                'longitude'      => 'nullable',
            ], [
                'reporter_name.required'  => 'Mohon isi nama Anda.',
                'customer_id.required'    => 'Mohon isi No. Pelanggan Anda.',
                'reporter_phone.required' => 'Mohon isi nomor HP.',
                'title.required'          => 'Mohon pilih jenis gangguan.',
                'address.required'        => 'Mohon isi alamat lokasi.',
                'kecamatan_id.required'   => 'Mohon pilih kecamatan.',
            ]);


            // Photo upload has been removed as per new requirements
            $photoPath = null;

            // ticket_code auto-generated by FieldJob::boot()
            $job = FieldJob::create([
                'reporter_name'  => $request->reporter_name,
                'customer_id'    => $request->customer_id,
                'reporter_phone' => $request->reporter_phone,
                'source'         => 'public',
                'title'          => $request->title,
                'address'        => $request->address,
                'kecamatan_id'   => $request->kecamatan_id,
                'description'    => $request->description,
                'photo_before'   => $photoPath,
                'latitude'       => $request->latitude,
                'longitude'      => $request->longitude,
                'status'         => 'pending',
            ]);

            // Broadcast to technicians via Telegram and WhatsApp
            try {
                $telegram = new TelegramService();
                $telegram->broadcastJob($job);
            } catch (\Exception $e) {
                \Log::warning('Telegram broadcast failed: ' . $e->getMessage());
            }

            try {
                $fonnte = new \App\Services\FonnteService();
                $fonnte->broadcastJob($job);
            } catch (\Exception $e) {
                \Log::warning('Fonnte broadcast failed: ' . $e->getMessage());
            }

            return response()->json([
                'success'     => true,
                'ticket_code' => $job->ticket_code,
                'message'     => 'Laporan berhasil dikirim!',
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'errors'  => $e->errors(),
            ], 422);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan server: ' . $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Track ticket status (Blade page — initial load)
     */
    public function trackTicket(Request $request)
    {
        $ticket = null;
        $ticketCode = $this->sanitizeTicketCode($request->query('kode'));

        if ($ticketCode) {
            $ticket = FieldJob::with(['kecamatan', 'user:id,name,phone,photo'])
                ->where('ticket_code', $ticketCode)
                ->first();
        }

        return view('pages.public.track', compact('ticket', 'ticketCode'));
    }

    /**
     * JSON API for auto-refresh polling (public, rate-limited)
     */
    public function getTicketJson(Request $request)
    {
        $ticketCode = $this->sanitizeTicketCode($request->query('kode'));

        if (!$ticketCode) {
            return response()->json(['error' => 'Kode tiket wajib diisi.'], 422);
        }

        $ticket = FieldJob::with(['kecamatan:id,nama', 'user:id,name,phone,photo'])
            ->where('ticket_code', $ticketCode)
            ->first();

        if (!$ticket) {
            return response()->json(['error' => 'Tiket tidak ditemukan.'], 404);
        }

        // Return only fields needed by the frontend
        return response()->json([
            'id'             => $ticket->id,
            'ticket_code'    => $ticket->ticket_code,
            'title'          => $ticket->title,
            'address'        => $ticket->address,
            'status'         => $ticket->status,
            'reporter_name'  => $ticket->reporter_name,
            'reporter_phone' => $ticket->reporter_phone,
            'photo_before'   => $ticket->photo_before,
            'photo_after'    => $ticket->photo_after,
            'estimated_time' => $ticket->estimated_time,
            'rating'         => $ticket->rating,
            'rating_feedback'=> $ticket->rating_feedback,
            'created_at'     => $ticket->created_at,
            'started_at'     => $ticket->started_at,
            'finished_at'    => $ticket->finished_at,
            'cancelled_at'   => $ticket->cancelled_at,
            'kecamatan'      => $ticket->kecamatan,
            'user'           => $ticket->user ? [
                'name'  => $ticket->user->name,
                'phone' => $ticket->user->phone,
                'photo' => $ticket->user->photo,
            ] : null,
        ]);
    }

    /**
     * Submit CSAT rating (public, rate-limited)
     */
    public function submitRating(Request $request)
    {
        $request->validate([
            'ticket_code'    => 'required|string|max:20',
            'rating'         => 'required|integer|min:1|max:5',
            'feedback'       => 'nullable|string|max:500',
        ]);

        $ticket = FieldJob::where('ticket_code', $this->sanitizeTicketCode($request->ticket_code))
            ->first();

        if (!$ticket) {
            return response()->json(['success' => false, 'message' => 'Tiket tidak ditemukan.'], 404);
        }

        // Only completed tickets can be rated
        if ($ticket->status !== 'selesai') {
            return response()->json(['success' => false, 'message' => 'Tiket belum selesai.'], 422);
        }

        // Prevent double rating
        if ($ticket->rating !== null) {
            return response()->json(['success' => false, 'message' => 'Anda sudah memberikan penilaian.'], 422);
        }

        $ticket->update([
            'rating'          => $request->rating,
            'rating_feedback' => $request->feedback,
        ]);

        return response()->json(['success' => true, 'message' => 'Terima kasih atas penilaian Anda!']);
    }

    /**
     * Cancel a ticket (public, rate-limited)
     */
    public function cancelTicket(Request $request)
    {
        $request->validate([
            'ticket_code'    => 'required|string|max:20',
        ]);

        $ticket = FieldJob::where('ticket_code', $this->sanitizeTicketCode($request->ticket_code))
            ->first();

        if (!$ticket) {
            return response()->json(['success' => false, 'message' => 'Tiket tidak ditemukan.'], 404);
        }

        // Only pending tickets can be cancelled by the reporter
        if ($ticket->status !== 'pending') {
            return response()->json(['success' => false, 'message' => 'Tiket sudah tidak bisa dibatalkan karena sedang/sudah diproses.'], 422);
        }

        $ticket->update([
            'status'       => 'dibatalkan',
            'cancelled_at' => now(),
        ]);

        return response()->json(['success' => true, 'message' => 'Laporan berhasil dibatalkan.']);
    }

    /**
     * Sanitize ticket code input to prevent injection
     */
    private function sanitizeTicketCode(?string $code): ?string
    {
        if (!$code) return null;
        // Ticket codes follow format: TSA-MMYY-XXXX — only allow alphanumeric + dash
        return preg_replace('/[^A-Za-z0-9\-]/', '', $code);
    }

    /**
     * Calculate average response time in minutes
     */
    private function getAverageResponse()
    {
        $jobs = FieldJob::whereNotNull('started_at')->get();
        if ($jobs->isEmpty()) return 0;

        $totalMinutes = 0;
        foreach ($jobs as $job) {
            $totalMinutes += $job->created_at->diffInMinutes($job->started_at);
        }
        return round($totalMinutes / $jobs->count());
    }
}
